# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276666308a980a44214fd820e68a91c0e01fd83870d149ed6559fb94f8fe966e14b6f0e861886829601b3fc930c686a369af5d6fb83a3d31826490818e4cd26f

test:
  secret_key_base: 96029b1e589e3dd14cf9f43fd45b4ae086313ba22cc083c435c95f62a8f50c7466c39b98bd146f8907b448b4d590e86923552cc8c1db738eaabb6c5c0c5263f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
